/*
 * This file is generated by jOOQ.
 */
package com.github.skapral.poetryclub.db.jooq;


import com.github.skapral.poetryclub.db.jooq.tables.Account;
import com.github.skapral.poetryclub.db.jooq.tables.Community;
import com.github.skapral.poetryclub.db.jooq.tables.Contribution;
import com.github.skapral.poetryclub.db.jooq.tables.Feedback;
import com.github.skapral.poetryclub.db.jooq.tables.FlywaySchemaHistory;
import com.github.skapral.poetryclub.db.jooq.tables.Member;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACCOUNT_PKEY = Indexes0.ACCOUNT_PKEY;
    public static final Index COMMUNITY_PKEY = Indexes0.COMMUNITY_PKEY;
    public static final Index CONTRIBUTION_PKEY = Indexes0.CONTRIBUTION_PKEY;
    public static final Index FEEDBACK_PKEY = Indexes0.FEEDBACK_PKEY;
    public static final Index FLYWAY_SCHEMA_HISTORY_PK = Indexes0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Indexes0.FLYWAY_SCHEMA_HISTORY_S_IDX;
    public static final Index MEMBER_PKEY = Indexes0.MEMBER_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ACCOUNT_PKEY = Internal.createIndex("account_pkey", Account.ACCOUNT, new OrderField[] { Account.ACCOUNT.ID }, true);
        public static Index COMMUNITY_PKEY = Internal.createIndex("community_pkey", Community.COMMUNITY, new OrderField[] { Community.COMMUNITY.ID }, true);
        public static Index CONTRIBUTION_PKEY = Internal.createIndex("contribution_pkey", Contribution.CONTRIBUTION, new OrderField[] { Contribution.CONTRIBUTION.ID }, true);
        public static Index FEEDBACK_PKEY = Internal.createIndex("feedback_pkey", Feedback.FEEDBACK, new OrderField[] { Feedback.FEEDBACK.ID }, true);
        public static Index FLYWAY_SCHEMA_HISTORY_PK = Internal.createIndex("flyway_schema_history_pk", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
        public static Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex("flyway_schema_history_s_idx", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
        public static Index MEMBER_PKEY = Internal.createIndex("member_pkey", Member.MEMBER, new OrderField[] { Member.MEMBER.ACCOUNTID, Member.MEMBER.COMMUNITYID }, true);
    }
}
