/*
 * This file is generated by jOOQ.
 */
package com.github.skapral.poetryclub.db.jooq;


import com.github.skapral.poetryclub.db.jooq.tables.Account;
import com.github.skapral.poetryclub.db.jooq.tables.Community;
import com.github.skapral.poetryclub.db.jooq.tables.Contribution;
import com.github.skapral.poetryclub.db.jooq.tables.Feedback;
import com.github.skapral.poetryclub.db.jooq.tables.FlywaySchemaHistory;
import com.github.skapral.poetryclub.db.jooq.tables.Member;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 532427814;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.account</code>.
     */
    public final Account ACCOUNT = com.github.skapral.poetryclub.db.jooq.tables.Account.ACCOUNT;

    /**
     * The table <code>public.community</code>.
     */
    public final Community COMMUNITY = com.github.skapral.poetryclub.db.jooq.tables.Community.COMMUNITY;

    /**
     * The table <code>public.contribution</code>.
     */
    public final Contribution CONTRIBUTION = com.github.skapral.poetryclub.db.jooq.tables.Contribution.CONTRIBUTION;

    /**
     * The table <code>public.feedback</code>.
     */
    public final Feedback FEEDBACK = com.github.skapral.poetryclub.db.jooq.tables.Feedback.FEEDBACK;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.github.skapral.poetryclub.db.jooq.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.member</code>.
     */
    public final Member MEMBER = com.github.skapral.poetryclub.db.jooq.tables.Member.MEMBER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ACCOUNT_ID,
            Sequences.COMMUNITY_ID,
            Sequences.CONTRIBUTION_ID,
            Sequences.FEEDBACK_ID,
            Sequences.REPORT_ID);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Account.ACCOUNT,
            Community.COMMUNITY,
            Contribution.CONTRIBUTION,
            Feedback.FEEDBACK,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Member.MEMBER);
    }
}
