/*
 * This file is generated by jOOQ.
 */
package com.github.skapral.poetryclub.db.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.account_id</code>
     */
    public static final Sequence<Long> ACCOUNT_ID = new SequenceImpl<Long>("account_id", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.community_id</code>
     */
    public static final Sequence<Long> COMMUNITY_ID = new SequenceImpl<Long>("community_id", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.contribution_id</code>
     */
    public static final Sequence<Long> CONTRIBUTION_ID = new SequenceImpl<Long>("contribution_id", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.feedback_id</code>
     */
    public static final Sequence<Long> FEEDBACK_ID = new SequenceImpl<Long>("feedback_id", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.report_id</code>
     */
    public static final Sequence<Long> REPORT_ID = new SequenceImpl<Long>("report_id", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
