/*
 * This file is generated by jOOQ.
 */
package com.github.skapral.poetryclub.db.jooq;


import com.github.skapral.poetryclub.db.jooq.tables.Account;
import com.github.skapral.poetryclub.db.jooq.tables.Community;
import com.github.skapral.poetryclub.db.jooq.tables.Contribution;
import com.github.skapral.poetryclub.db.jooq.tables.Feedback;
import com.github.skapral.poetryclub.db.jooq.tables.FlywaySchemaHistory;
import com.github.skapral.poetryclub.db.jooq.tables.Member;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT = com.github.skapral.poetryclub.db.jooq.tables.Account.ACCOUNT;

    /**
     * The table <code>public.community</code>.
     */
    public static final Community COMMUNITY = com.github.skapral.poetryclub.db.jooq.tables.Community.COMMUNITY;

    /**
     * The table <code>public.contribution</code>.
     */
    public static final Contribution CONTRIBUTION = com.github.skapral.poetryclub.db.jooq.tables.Contribution.CONTRIBUTION;

    /**
     * The table <code>public.feedback</code>.
     */
    public static final Feedback FEEDBACK = com.github.skapral.poetryclub.db.jooq.tables.Feedback.FEEDBACK;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.github.skapral.poetryclub.db.jooq.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.member</code>.
     */
    public static final Member MEMBER = com.github.skapral.poetryclub.db.jooq.tables.Member.MEMBER;
}
