/*
 * This file is generated by jOOQ.
 */
package com.github.skapral.poetryclub.db.jooq.tables.records;


import com.github.skapral.poetryclub.db.jooq.tables.Member;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemberRecord extends UpdatableRecordImpl<MemberRecord> implements Record4<Long, Long, String, Timestamp> {

    private static final long serialVersionUID = -367799814;

    /**
     * Setter for <code>public.member.accountid</code>.
     */
    public void setAccountid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.member.accountid</code>.
     */
    public Long getAccountid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.member.communityid</code>.
     */
    public void setCommunityid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.member.communityid</code>.
     */
    public Long getCommunityid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.member.role</code>.
     */
    public void setRole(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.member.role</code>.
     */
    public String getRole() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.member.timestamp</code>.
     */
    public void setTimestamp(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.member.timestamp</code>.
     */
    public Timestamp getTimestamp() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, String, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, String, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Member.MEMBER.ACCOUNTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Member.MEMBER.COMMUNITYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Member.MEMBER.ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Member.MEMBER.TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getAccountid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getCommunityid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getAccountid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getCommunityid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberRecord value1(Long value) {
        setAccountid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberRecord value2(Long value) {
        setCommunityid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberRecord value3(String value) {
        setRole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberRecord value4(Timestamp value) {
        setTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberRecord values(Long value1, Long value2, String value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MemberRecord
     */
    public MemberRecord() {
        super(Member.MEMBER);
    }

    /**
     * Create a detached, initialised MemberRecord
     */
    public MemberRecord(Long accountid, Long communityid, String role, Timestamp timestamp) {
        super(Member.MEMBER);

        set(0, accountid);
        set(1, communityid);
        set(2, role);
        set(3, timestamp);
    }
}
